// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-v4iyUVQrksUrw6W4zFyJnwIiaM5B94',
    appId: '1:18169442499:web:296d92d852c07bad123276',
    messagingSenderId: '18169442499',
    projectId: 'rentkaro8865',
    authDomain: 'rentkaro8865.firebaseapp.com',
    storageBucket: 'rentkaro8865.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFz9KTP7LizkAGn93iby_sOCYM29iX34',
    appId: '1:18169442499:android:75ef8b1523b29760123276',
    messagingSenderId: '18169442499',
    projectId: 'rentkaro8865',
    storageBucket: 'rentkaro8865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWsZf7ug0S_ScgWLWIkCTvcw_Jsq9N7xk',
    appId: '1:18169442499:ios:1157708aecf4d14d123276',
    messagingSenderId: '18169442499',
    projectId: 'rentkaro8865',
    storageBucket: 'rentkaro8865.firebasestorage.app',
    iosBundleId: 'com.example.rentkaroFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWsZf7ug0S_ScgWLWIkCTvcw_Jsq9N7xk',
    appId: '1:18169442499:ios:1157708aecf4d14d123276',
    messagingSenderId: '18169442499',
    projectId: 'rentkaro8865',
    storageBucket: 'rentkaro8865.firebasestorage.app',
    iosBundleId: 'com.example.rentkaroFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-v4iyUVQrksUrw6W4zFyJnwIiaM5B94',
    appId: '1:18169442499:web:393ba6f2754150c8123276',
    messagingSenderId: '18169442499',
    projectId: 'rentkaro8865',
    authDomain: 'rentkaro8865.firebaseapp.com',
    storageBucket: 'rentkaro8865.firebasestorage.app',
  );

}